#
# Index config file for gh-archive dataset.
#

version: 0.6

index_id: "Fetchevent"
index_uri: "s3://openreplay-quickwit/quickwit-indexes/fetchevent"

doc_mapping:
  mode: dynamic
  field_mappings:
    - name: insertion_timestamp
      type: datetime
      input_formats:
        - unix_timestamp
      precision: seconds
      fast: true
    - name: project_id
      type: i64
      fast: true
    - name: session_id
      type: i64
      fast: true
    - name: message_id
      type: i64
      fast: true
    - name: method
      type: text
      tokenizer: default
      record: position
    - name: url
      type: text
      tokenizer: default
      record: position
    - name: request
      type: json
      stored: true
      indexed: true
      tokenizer: default
      record: position
    - name: response
      type: json
      stored: true
      indexed: true
      tokenizer: default
      record: position
    - name: status
      type: i64
      indexed: true
      fast: true
    - name: timestamp
      type: i64
      fast: true
    - name: duration
      type: i64
      fast: true
  timestamp_field: insertion_timestamp

search_settings:
  default_search_fields: [project_id, session_id, url]

retention:
  period: 30 days
  schedule: hourly

indexing_settings:
  merge_policy:
    type: "stable_log"
    min_level_num_docs: 40000
    maturation_period: 12h
