## In order to save data into S3
# metastore also accepts s3://{bucket/path}#pooling_interval={seconds}s
version: {{QUICKWIT_VERSION}}
metastore_uri: s3://openreplay-quickwit/quickwit-indexes
default_index_root_uri: s3://openreplay-quickwit/quickwit-indexes
rest_listen_port: {{QUICKWIT_PORT}}
